Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-08, with the labels that each got.

#89 feat: user 기능 변경 및 post 반환 데이터 추가
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/component/NotionDevComponent.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/component/oauth/NotionOAuthComponent.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/NoUserProfileDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/exception/NoProfileImageException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/message/ExceptionMessages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/notion/NotionService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/oauth/NotionOauthService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/post/PostService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/resources/application.yml
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
  003 Code/BE/notion-linked-blog/src/test/resources/application.yml
Labels: ☕BE, ✨FEAT, 🙏NEED REVIEW

#90 fix: user 기능추가시 누락부분 반영
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/UserWithoutPassword.java
Labels: ☕BE, ⚠️HOTFIX, 🍡SIMPLE

#92 feat: 노션 Oauth2.0 연동 2
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/notion/NotionApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/oauth/OAuthApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/notion/SyncedPages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/Post.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/exception/NotionAuthenticationException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/post/PostDataRepositoryImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/post/PostRepositoryCustom.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/syncedpages/SyncedPagesDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/notion/NotionService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/notion/UpdateNotionSchedule.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/oauth/NotionOauthService.java
Labels: ☕BE, ✨FEAT

#93 feat: 노션 연동 시 로딩 UI 처리
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/NotionLinking.tsx
  003 Code/FE/notion-linked-blog/src/pages/auth.tsx
Labels: 🌈FE, ✨FEAT

#95 fix 중복 테이블 삭제
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/notion/Notion.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/Post.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/notion/NotionDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/notion/NotionService.java
Labels: ☕BE, 🛠️FIX, 🍡SIMPLE
