Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-07, with the labels that each got.

#79 feat: 메인 페이지의 포스트카드에 썸네일 추가
  003 Code/FE/notion-linked-blog/src/apis/post.ts
  003 Code/FE/notion-linked-blog/src/apis/signup.ts
  003 Code/FE/notion-linked-blog/src/apis/user.ts
  003 Code/FE/notion-linked-blog/src/components/post/PostCard.tsx
Labels: 🌈FE, ✨FEAT

#80 feat: 프로파일 삭제 매서드 추가 및 기타 오류 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/ExceptionMessages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/UserWithoutPassword.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/resources/static/images/defaultImageFile.png
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
Labels: ☕BE, 🛠️FIX, ✨FEAT

#78 feat: 유저 정보 수정 기능 개발
  003 Code/FE/notion-linked-blog/src/apis/user.ts
  003 Code/FE/notion-linked-blog/src/components/setting/BottomInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/Common.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/TopInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/BlogInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/BottomInfoItem.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/SettingSubtitle.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/Signout.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/SocialInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/top/Introduction.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/top/Profile.tsx
  003 Code/FE/notion-linked-blog/src/redux/userSlice.ts
Labels: 🌈FE, ✨FEAT

#81 fix: 로그인 상태 확인 응답으로 Authentication.User -> UserDataRepository.User
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/filter/LoginStatusCheckingFilter.java
Labels: ☕BE, 🛠️FIX

#84 fix: Comments API 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/comments/CommentsApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/comments/Comments.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/comments/dto/CommentSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/comments/dto/response/ChildCommentDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/comments/dto/response/CommentEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/comments/dto/response/ParentsCommentDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/comments/CommentsDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/comments/CommentsService.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/comments/CommentsApiControllerTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/comments/CommentsServiceTest.java
Labels: 📝DOCS, ☕BE, 🛠️FIX, 🐞BUG

#86 refactor: useInfiniteScroll의 IntersectionObserver를 useEffect 내부로 이동
  003 Code/FE/notion-linked-blog/src/components/common/AppLayout.tsx
  003 Code/FE/notion-linked-blog/src/components/post/MainPosts.tsx
  003 Code/FE/notion-linked-blog/src/hooks/useInfiniteScroll.ts
  003 Code/FE/notion-linked-blog/src/pages/_app.tsx
Labels: 🌈FE, ♻️REFACTOR
