Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-10, with the labels that each got.

#102 feat: notion 연동 기능 개선 및 강화
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/NotionApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/port/NotionService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/SyncedPages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/dto/CreateNotionPageToBlogDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoContentException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/UpdateNotionSchedule.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedPagesRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedSeriesRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/api/OAuthApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/service/NotionOauthServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserEntity.java
Labels: ☕BE, ✨FEAT

#103 fix: props 오류로 인한 빌드 에러 수정
  003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx
Labels: 🌈FE, 🛠️FIX

#105 fix: 변수 이름 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/CommentsApiController.java
Labels: ☕BE, 🐞BUG, ⚠️HOTFIX

#106 feat: 배포를 위한 환경 분리 및 dockerfile작성
  003 Code/BE/notion-linked-blog/Dockerfile
  003 Code/BE/notion-linked-blog/build.gradle
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/EmbeddedRedisConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/RedisConfig.java
Labels: ☕BE, ✨FEAT

#111 fix: profile 이미지 삭제 오류 해결
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/port/UserService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/UserServiceImpl.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/user/api/UserApiControllerTests.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#112 fix: comment에 바뀐 profileImage 경로 반영 안되는 버그 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/response/ChildCommentDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/response/ParentsCommentDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/service/CommentsServiceImpl.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/comments/service/CommentsServiceTest.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#114 fix: 이미지 관련 next.config.js 수정
  003 Code/FE/notion-linked-blog/next.config.js
  003 Code/FE/notion-linked-blog/src/components/post/comment/Comment.tsx
  003 Code/FE/notion-linked-blog/src/components/post/comment/Reply.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/top/Profile.tsx
Labels: 🌈FE, 🛠️FIX

#115 feat: userId로 post와 series 검색 매서드 추가
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostQuerydslRepositoryImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/PostServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesQuerydslRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/port/UserService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/response/UserPostsDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/response/UserSeriesDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/domain/dto/UserSeriesInfoDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/UserServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserPostQuerydslRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserSeriesQuerydslRepository.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/service/PostServiceTest.java
Labels: ☕BE, ✨FEAT

#116 feat: 내 블로그 기능 개발
  003 Code/FE/notion-linked-blog/src/apis/user.ts
  003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx
  003 Code/FE/notion-linked-blog/src/components/common/menuItemData.json
  003 Code/FE/notion-linked-blog/src/pages/[author]/index.tsx
Labels: 🌈FE, ✨FEAT

#117 fix: swagger오류 임시 해결
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java
Labels: ☕BE, 🪣CHORE, 🐞BUG

#118 fix: series리턴파라미터 추가 및 Series에서 내려주는 ThumbnailUrl 변경
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/SeriesApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/port/SeriesService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/SeriesDetailSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/SeriesSimpleSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/UserSeriesResponseDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesQuerydslRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/service/SeriesServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/domain/dto/UserSeriesInfoDto.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/series/service/SeriesServiceTest.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#120 fix: series관련 api 수정 및 예외처리 추가
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/PostApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/SeriesApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/port/SeriesService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/PostForDetailSeries.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/exception/SeriesNotExistException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/service/SeriesServiceImpl.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/series/service/SeriesServiceTest.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#121 fix: convertPathToId 에서 쿼리 파라미터를 분리하지 못하는 문제 해결
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java
Labels: ☕BE, 🛠️FIX

#122 fix: 예외처리 및 Token조회 관련 버그 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/NotionApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/port/NotionService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoAccessTokenException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoTitleException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/UpdateNotionSchedule.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/api/OAuthApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#123 feat: 노션 페이지 연동 기능 개발
  003 Code/FE/notion-linked-blog/src/apis/notion.ts
  003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/NotionLinking.tsx
  003 Code/FE/notion-linked-blog/src/pages/[author]/series/[seriesname]/index.tsx
  003 Code/FE/notion-linked-blog/src/pages/write/index.tsx
  003 Code/FE/notion-linked-blog/src/pages/write/notion/index.tsx
  003 Code/FE/notion-linked-blog/src/pages/write/self/index.tsx
Labels: 🌈FE, ✨FEAT

#124 docs: README 수정
  README.md
  img/F12-ERD.png
  img/F12-ERD_old3.png
  img/F12_DevArchitecture.jpg
  img/F12_ProductArchitecture.jpg
  img/F12_System_Requirements.jpg
  img/class-diagram.png
Labels: 📝DOCS

#127 docs: README 이미지 위치 변경
  README.md
Labels: 📝DOCS
