Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-05, with the labels that each got.

#17 feat: 이메일 기반 회원가입 유저에 대한 로그인 기능 개발 및 테스트
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/login/email/EmailLoginUserRequestDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/common/dto/AuthenticationFailureDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/configure/AjaxLoginConfigurer.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/AjaxLoginFailureDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/AjaxLoginSuccessDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/LoginUser.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/exception/EmailNotFoundException.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/filter/AjaxEmailPasswordAuthenticationFilter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/handler/AjaxAuthenticationFailureHandler.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/handler/AjaxAuthenticationSuccessHandler.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/provider/AjaxEmailPasswordAuthenticationProvider.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/service/EmailUserDetailsService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/token/AjaxEmailPasswordAuthenticationToken.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/resources/data.sql
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserRepositoryTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/security/login/ajax/filter/AjaxEmailPasswordAuthenticationFilterTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
Labels: ☕BE, 🛠️FIX, ✨FEAT, 🙏NEED REVIEW

#20 feat: post 기능 개발
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/PostTimeEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/Post.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/dto/PostCreateDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/dto/PostEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/dto/PostSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/dto/SearchRequestDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/series/Series.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/ExceptionMessages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/post/PostDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/post/PostService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/resources/data.sql
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/post/PostDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/post/PostServiceTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
Labels: ♻️REFACTOR, ☕BE, ✨FEAT, 🙏NEED REVIEW

#22 feat: 이메일 기반 로그인 유저에 대한 로그아웃 기능 개발
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/NotionLinkedBlogApplicationTests.java
Labels: ☕BE, ✨FEAT

#23 fix: 이메일 인증 코드 요청 전 이메일 중복 검증 로직 추가
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/EmailApiController.java
  003 Code/BE/notion-linked-blog/src/main/resources/data.sql
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/EmailApiControllerTests.java
Labels: ☕BE, 🛠️FIX, 🐞BUG

#24 fix: 로그인 시 프론트에 유저 정보를 내려주기 위해 로그인 정보 저장 관련
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/AjaxLoginSuccessDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/LoginUser.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/UserWithoutPassword.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/handler/AjaxAuthenticationSuccessHandler.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/service/EmailUserDetailsService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/token/AjaxEmailPasswordAuthenticationToken.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/security/login/ajax/filter/AjaxEmailPasswordAuthenticationFilterTests.java
Labels: ☕BE, 🛠️FIX, 🚨URGENT

#25 fix: 로그아웃 API 경로 /logout -> /api/logout 으로 변경
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
Labels: ☕BE, 🛠️FIX, 🍡SIMPLE

#26 feat: 로그인 및 회원가입 컴포넌트 및 기능 개발
  003 Code/FE/notion-linked-blog/next.config.js
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/apis/apiClient.js
  003 Code/FE/notion-linked-blog/src/apis/signup.js
  003 Code/FE/notion-linked-blog/src/apis/user.js
  003 Code/FE/notion-linked-blog/src/app/store.js
  003 Code/FE/notion-linked-blog/src/common/reset.css
  003 Code/FE/notion-linked-blog/src/components/auth/AuthForm.js
  003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/common.js
  003 Code/FE/notion-linked-blog/src/hooks/hooks.js
  003 Code/FE/notion-linked-blog/src/pages/_app.js
  003 Code/FE/notion-linked-blog/src/pages/index.js
  003 Code/FE/notion-linked-blog/src/redux/counterSlice.js
  003 Code/FE/notion-linked-blog/src/redux/store.js
  003 Code/FE/notion-linked-blog/src/redux/userSlice.js
Labels: 🌈FE, ✨FEAT

#28 fix: Post 생성 시 잘못된 HttpMethod 변경
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
Labels: ☕BE, 🐞BUG, ⚠️HOTFIX

#30 feat: 메인 페이지 레이아웃 구성 컴포넌트 개발
  003 Code/FE/notion-linked-blog/src/components/AppLayout.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostCard.jsx
  003 Code/FE/notion-linked-blog/src/pages/index.js
  003 Code/FE/notion-linked-blog/src/redux/counterSlice.js
  003 Code/FE/notion-linked-blog/src/redux/postSlice.js
  003 Code/FE/notion-linked-blog/src/redux/store.js
Labels: 🌈FE, ✨FEAT

#32 build: react-md-editor 추가 및 css 오류 수정
  003 Code/FE/notion-linked-blog/next.config.js
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/common/reset.css
  003 Code/FE/notion-linked-blog/src/pages/_app.js
Labels: 🌈FE, ✨FEAT, ⚠️HOTFIX, 🚨URGENT

#33 feat: styled-component에 ssr을 적용하여 페이지 로딩 시 styled-comopents 정상 적용
  003 Code/FE/notion-linked-blog/.babelrc
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/pages/_document.js
Labels: 🌈FE, ⚠️HOTFIX

#34 fix: Dotenv 설정이 제외되던 오류 해결
  003 Code/FE/notion-linked-blog/next.config.js
Labels: 🌈FE, ⚠️HOTFIX, 🔔Important

#36 test: test 순서가 보장되지 않아서 생기는 문제를 해결
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/post/PostDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
Labels: ☕BE, ⚠️HOTFIX, 🚨URGENT

#38 fix: 양방향 연관관계 설정 오류 해결
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/Post.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
Labels: ☕BE, 🐞BUG, ⚠️HOTFIX, 🚨URGENT

#41 feat: 로그인 상태 확인을 위한 API 개발
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/dto/LoginStatusCheckingFailureResponseDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/dto/LoginStatusCheckingSuccessResponseDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/filter/LoginStatusCheckingFilter.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/security/login/check/filter/LoginStatusCheckingFilterTests.java
Labels: ☕BE, ✨FEAT, 🐞BUG

#43 fix: 로그인 후 새로고침 시 로그인 상태가 풀리는 버그 수정 및 리팩토링
  003 Code/FE/notion-linked-blog/src/apis/apiClient.js
  003 Code/FE/notion-linked-blog/src/apis/user.js
  003 Code/FE/notion-linked-blog/src/components/AppLayout.jsx
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/common/AppLayout.jsx
  003 Code/FE/notion-linked-blog/src/pages/_app.js
Labels: 🌈FE, 🛠️FIX, 🐞BUG

#46 fix: 자원 접근에 대한 접근 정책 변경
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
Labels: ☕BE, ⚠️HOTFIX, 🔔Important

#44 feat: Swagger에 이메일 기반 로그인 및 로그인 상태 확인 API 추가
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/SwaggerConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/filter/AjaxEmailPasswordAuthenticationFilter.java
Labels: ☕BE, ✨FEAT

#48 feat: 메인 페이지 스타일 수정
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/common/AppLayout.jsx
  003 Code/FE/notion-linked-blog/src/components/post/MainPosts.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostCard.jsx
  003 Code/FE/notion-linked-blog/src/pages/index.js
  003 Code/FE/notion-linked-blog/src/redux/postSlice.js
  003 Code/FE/notion-linked-blog/src/utils/time.js
Labels: 🌈FE

#49 fix: Hydration 관련 오류 수정 및 Next.js에서 SSR, CSR Redux 통합
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/pages/_app.js
  003 Code/FE/notion-linked-blog/src/redux/store.js
Labels: 🛠️FIX, 🐞BUG

#50 feat: 포스트 작성 컴포넌트 개발
  003 Code/FE/notion-linked-blog/.eslintrc.json
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/src/apis/post.js
  003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/common.js
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/post/Post.js
  003 Code/FE/notion-linked-blog/src/components/post/PostWrite.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx
  003 Code/FE/notion-linked-blog/src/components/post/Uploader.jsx
  003 Code/FE/notion-linked-blog/src/pages/write.js
  003 Code/FE/notion-linked-blog/src/redux/postSlice.js
Labels: 🌈FE, ✨FEAT, 🔔Important

#54 feat: MainPosts에 무한 스크롤링 적용 및 postSlice 제거
  003 Code/FE/notion-linked-blog/.eslintrc.json
  003 Code/FE/notion-linked-blog/src/apis/post.js
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/common/AppLayout.jsx
  003 Code/FE/notion-linked-blog/src/components/post/MainPosts.jsx
  003 Code/FE/notion-linked-blog/src/hooks/useInfiniteScroll.js
  003 Code/FE/notion-linked-blog/src/pages/_app.js
  003 Code/FE/notion-linked-blog/src/redux/postSlice.js
  003 Code/FE/notion-linked-blog/src/redux/store.js
Labels: 🌈FE, ✨FEAT

#55 fix: 로그인 및 회원가입 오류 수정 및 개선
  003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx
  003 Code/FE/notion-linked-blog/src/components/auth/common.js
  003 Code/FE/notion-linked-blog/src/components/post/Post.js
  003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx
  003 Code/FE/notion-linked-blog/src/pages/write.js
Labels: 🌈FE, 🛠️FIX
