Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-04, with the labels that each got.

#9 feat: 이메일 인증 기반 회원가입 기능 개발
  003 Code/BE/notion-linked-blog/.gitignore
  003 Code/BE/notion-linked-blog/build.gradle
  003 Code/BE/notion-linked-blog/naver-checkstyle-rules.xml
  003 Code/BE/notion-linked-blog/naver-checkstyle-suppressions.xml
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/EmailApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/TestApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/EmailConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/EmbeddedRedisConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/RedisConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/WebConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/BaseTimeEntity.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/Tests.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/TestsRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/dto/TestsResponseDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/dto/TestsSaveRequestDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/dummy/DummyObject.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/signup/UserSignupRequestDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/signup/UserSignupResponseDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/verification/EmailVerificationToken.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/redis/EmailVerificationTokenRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/service/SecureRandomService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/EmailSignupService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/redis/EmailVerificationTokenService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/web/argumentresolver/email/Email.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/web/argumentresolver/email/EmailArgumentResolver.java
  003 Code/BE/notion-linked-blog/src/main/resources/application.yml
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/EmailApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/TestApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/domain/TestsRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/redis/EmailVerificationTokenRepositoryTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserRepositoryTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/security/service/SecureRandomServiceTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/EmailSignupServiceTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
  003 Code/BE/notion-linked-blog/src/test/resources/application.yml
Labels: ☕BE, ✨FEAT

#11 build: 프론트엔드 기본 개발 환경 세팅
  003 Code/FE/.idea/workspace.xml
  003 Code/FE/notion-linked-blog/.babelrc
  003 Code/FE/notion-linked-blog/.eslintrc.json
  003 Code/FE/notion-linked-blog/.gitignore
  003 Code/FE/notion-linked-blog/README.md
  003 Code/FE/notion-linked-blog/jsconfig.json
  003 Code/FE/notion-linked-blog/next.config.js
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/app/hooks.js
  003 Code/FE/notion-linked-blog/src/app/store.js
  003 Code/FE/notion-linked-blog/src/features/counter/counterSlice.js
  003 Code/FE/notion-linked-blog/src/pages/_app.js
  003 Code/FE/notion-linked-blog/src/pages/index.js
Labels: 🌈FE, 🍡SIMPLE

#13 feat: 유저 조회, 수정, 삭제 API개발
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/main/resources/application.yml
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
  003 Code/BE/notion-linked-blog/src/test/resources/application.yml
Labels: ☕BE, ✨FEAT

#15 fix: User, UserSearchDto 코드개선 및 Test코드 오타 수정, 변경 반영
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
Labels: ✅TEST, ♻️REFACTOR, ☕BE, 🛠️FIX

#16 Fix: UserApiController - editUserInfo 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
Labels: ☕BE, 🛠️FIX
