Repository HBNU-SWUNIV/come-capstone23-f12, pull requests merged in 2023-06, with the labels that each got.

#57 refactor: 회원가입 오류처리 코드 개선 및 포스트에서 보내는 데이터 추가
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx
  003 Code/FE/notion-linked-blog/src/pages/write.js
Labels: 🌈FE, ♻️REFACTOR

#58 feat: 개별 포스트 조회 기능 개발
  003 Code/FE/notion-linked-blog/src/apis/post.js
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/post/MainPosts.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostCard.jsx
  003 Code/FE/notion-linked-blog/src/components/post/PostViewer.jsx
  003 Code/FE/notion-linked-blog/src/pages/[author]/[id].js
  003 Code/FE/notion-linked-blog/src/utils/time.js
Labels: 🌈FE, ✨FEAT

#59 refactor: 401, 404에 대한 중복 코드를 Reflection을 활용하여 제거
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/EmailApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/comments/CommentsApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/SwaggerConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/common/CommonErrorResponse.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
  003 Code/BE/notion-linked-blog/src/main/resources/application.yml
  003 Code/BE/notion-linked-blog/src/main/resources/data.sql
Labels: ♻️REFACTOR, ☕BE

#60 feat: Update & Delete 컴포넌트 및 페이지 개발 및 버그 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/FE/notion-linked-blog/src/apis/post.js
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx
  003 Code/FE/notion-linked-blog/src/components/post/Post.js
  003 Code/FE/notion-linked-blog/src/components/post/PostViewer.jsx
  003 Code/FE/notion-linked-blog/src/pages/[author]/[id].js
  003 Code/FE/notion-linked-blog/src/pages/write/[id].js
  003 Code/FE/notion-linked-blog/src/pages/write/index.js
Labels: 🌈FE, ✨FEAT

#61 fix: PostApiControllerTest의 포스트 수정 이슈 해결
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
Labels: ☕BE, 🛠️FIX, 🍡SIMPLE

#63 fix: 모든 HTTP 응답에 charset=utf-8이 붙는 오류 수정
  003 Code/BE/notion-linked-blog/src/main/resources/application.yml
Labels: ☕BE, 🐞BUG

#64 fix: Post 조회시 Like 상태 조회 추가 및 Test 수정
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/comments/CommentsApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/post/PostApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/post/dto/PostSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/post/PostService.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/comments/CommentsServiceTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/post/PostServiceTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
  003 Code/BE/notion-linked-blog/testImage.png
Labels: 📝DOCS, ✅TEST, ☕BE, 🪣CHORE, 🐞BUG

#65 docs: 캡스톤디자인 1 중간 및 최종보고서 추가
  001 Report/캡스톤디자인I 중간보고서.pdf
  001 Report/캡스톤디자인I 최종보고서.pdf
Labels: 📝DOCS

#66 refactor: JS -> TS로 컨버팅
  003 Code/FE/notion-linked-blog/.eslintrc.json
  003 Code/FE/notion-linked-blog/jsconfig.json
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/apis/apiClient.ts
  003 Code/FE/notion-linked-blog/src/apis/post.ts
  003 Code/FE/notion-linked-blog/src/apis/signup.ts
  003 Code/FE/notion-linked-blog/src/apis/user.ts
  003 Code/FE/notion-linked-blog/src/components/auth/AuthForm.ts
  003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.tsx
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.tsx
  003 Code/FE/notion-linked-blog/src/components/auth/common.ts
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.tsx
  003 Code/FE/notion-linked-blog/src/components/common/AppLayout.tsx
  003 Code/FE/notion-linked-blog/src/components/post/MainPosts.tsx
  003 Code/FE/notion-linked-blog/src/components/post/Post.ts
  003 Code/FE/notion-linked-blog/src/components/post/PostCard.tsx
  003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx
  003 Code/FE/notion-linked-blog/src/components/post/PostWrite.tsx
  003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.tsx
  003 Code/FE/notion-linked-blog/src/components/post/Uploader.tsx
  003 Code/FE/notion-linked-blog/src/hooks/hooks.js
  003 Code/FE/notion-linked-blog/src/hooks/useInfiniteScroll.ts
  003 Code/FE/notion-linked-blog/src/pages/[author]/[id].tsx
  003 Code/FE/notion-linked-blog/src/pages/_app.tsx
  003 Code/FE/notion-linked-blog/src/pages/_document.tsx
  003 Code/FE/notion-linked-blog/src/pages/index.tsx
  003 Code/FE/notion-linked-blog/src/pages/write/[id].tsx
  003 Code/FE/notion-linked-blog/src/pages/write/index.tsx
  003 Code/FE/notion-linked-blog/src/redux/store.ts
  003 Code/FE/notion-linked-blog/src/redux/userSlice.ts
  003 Code/FE/notion-linked-blog/src/utils/time.ts
  003 Code/FE/notion-linked-blog/tsconfig.json
Labels: 🌈FE, ♻️REFACTOR, 🔔Important

#67 refactor: 사용자 드롭다운 메뉴 리팩토링
  003 Code/FE/notion-linked-blog/src/components/common/AppHeader.tsx
  003 Code/FE/notion-linked-blog/src/components/common/MenuItem.tsx
  003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx
  003 Code/FE/notion-linked-blog/src/pages/logout/index.tsx
  003 Code/FE/notion-linked-blog/src/types/index.ts
Labels: 🌈FE, ♻️REFACTOR

#69 feat: 회원 가입 시 기타 필드 추가
  003 Code/FE/notion-linked-blog/src/apis/signup.ts
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.tsx
  003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx
  003 Code/FE/notion-linked-blog/src/pages/write/[id].tsx
Labels: 🌈FE, ✨FEAT

#70 feat: 사용자 정보 수정 페이지 및 컴포넌트 개발, 회원탈퇴 기능 개발
  003 Code/FE/notion-linked-blog/src/apis/user.ts
  003 Code/FE/notion-linked-blog/src/components/setting/BottomInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/TopInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/BlogInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/BottomInfoItem.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/SettingSubtitle.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/Signout.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/bottom/SocialInfo.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/top/Introduction.tsx
  003 Code/FE/notion-linked-blog/src/components/setting/top/Profile.tsx
  003 Code/FE/notion-linked-blog/src/pages/setting/index.tsx
Labels: 🌈FE, ✨FEAT

#72 refactor: 가독성 향상을 위한 MenuItemsDropdown 리팩토링
  003 Code/FE/notion-linked-blog/src/components/common/MenuItem.tsx
  003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx
  003 Code/FE/notion-linked-blog/src/components/common/menuItemData.json
  003 Code/FE/notion-linked-blog/src/types/index.ts
Labels: 🌈FE, ♻️REFACTOR

#71 fix: encoding 문제 해결
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/Utf8Filter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/WebConfig.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
Labels: ☕BE, 🛠️FIX, 🐞BUG, 🙏NEED REVIEW

#74 feat: 댓글 컴포넌트 개발
  003 Code/FE/notion-linked-blog/package-lock.json
  003 Code/FE/notion-linked-blog/package.json
  003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.tsx
  003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.tsx
  003 Code/FE/notion-linked-blog/src/components/post/comment/Comment.tsx
  003 Code/FE/notion-linked-blog/src/components/post/comment/CommentContainer.tsx
  003 Code/FE/notion-linked-blog/src/components/post/comment/CommentForm.tsx
  003 Code/FE/notion-linked-blog/src/components/post/comment/CommentWriterDetails.tsx
  003 Code/FE/notion-linked-blog/src/pages/[author]/[id].tsx
Labels: 🌈FE, ✨FEAT

#73 fix: User 정보수정 Api 분리
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/Utf8Filter.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/request/ProfileSuccessEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/request/UserBasicInfoEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/request/UserBlogTitleEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/request/UserSocialInfoEditDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/UserSearchDto.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/ExceptionMessages.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/post/PostService.java
  003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
  003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
Labels: 🛠️FIX, 🪣CHORE
